// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearStartDirectories() {
  return window['go']['main']['App']['ClearStartDirectories']();
}

export function FindDuplicates() {
  return window['go']['main']['App']['FindDuplicates']();
}

export function OpenHostLocation(arg1) {
  return window['go']['main']['App']['OpenHostLocation'](arg1);
}

export function RemoveStartDirectory(arg1) {
  return window['go']['main']['App']['RemoveStartDirectory'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SelectStartDirectories() {
  return window['go']['main']['App']['SelectStartDirectories']();
}
