// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearStartDirectories():Promise<Array<string>>;

export function FindDuplicates():Promise<void>;

export function OpenHostLocation(arg1:string):Promise<void>;

export function RemoveStartDirectory(arg1:string):Promise<Array<string>>;

export function Reset():Promise<void>;

export function SelectStartDirectories():Promise<Array<string>>;
